apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
  labels:
    app: kuard
    tier: frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: kuard
        tier: frontend
        version: "2"
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:2"
