Makefile
21/08/2021

Reference:	YouTube.txt

SavvyNik
C++ Tutorial for Beginners #2: Visual Studio Code - Makefile & Multi File Extension | 2021 | (Linux)
https://www.youtube.com/watch?v=whQQF4kVjPY&t=513s

C++ Tutorial for Beginners #10: Debugging Makefile Project with Visual Studio Code IDE | (Linux GDB)
https://www.youtube.com/watch?v=9VpiGwp8Vos




SOURCE CODE
E:\GitHub\StevePro7\Blogger\Linux\MyCCpp\vscode_setup