kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: stevepro-aws-eks
  region: eu-west-1
  version: "1.27"
  tags:
    createdBy: stevepro

kubernetesNetworkConfig:
  ipFamily: IPv4

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
    roleOnly: true
    roleName: stevepro-aws-eks-AmazonEKS_EBS_CSI_DriverRole

addons:
- name: aws-ebs-csi-driver
  version: v1.38.1-eksbuild.2
  serviceAccountRoleARN: arn:aws:iam::476230071208:role/stevepro-aws-eks-AmazonEKS_EBS_CSI_DriverRole
- name: vpc-cni
  version: v1.19.2-eksbuild.1
- name: coredns
  version: v1.10.1-eksbuild.18
- name: kube-proxy
  version: v1.27.16-eksbuild.14

nodeGroups:
  - name: stevepro-aws-eks
    instanceType: m5.large
    desiredCapacity: 0
    minSize: 0
    maxSize: 3
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/master_ssh_key.pub   
    preBootstrapCommands:
      - "true"
