kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: stevepro-aws-eks02
  region: eu-west-1

nodeGroups:
  - name: stevepro-aws-eks02
    instanceType: m5.large
    desiredCapacity: 1

cloudWatch:
    clusterLogging:
      enableTypes: ["all"]
