kind: Pod
apiVersion: v1
metadata:
  name: use-service-account-pod
spec:
  serviceAccountName: my-service-account
  containers:
  - name: container-service-account
    image: nginx:1.7.9
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
